Added special windows hacks to try to normalize things a bit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,6 +26,11 @@ jobs:
         java: [adopt@1.8]
     runs-on: ${{ matrix.os }}
     steps:
+      - name: Ignore line ending differences in git
+        if: contains(runner.os, 'windows')
+        shell: bash
+        run: git config --global core.autocrlf false
+
       - name: Checkout current branch (fast)
         uses: actions/checkout@v2
 
@@ -33,6 +38,59 @@ jobs:
         uses: olafurpg/setup-scala@v5
         with:
           java-version: ${{ matrix.java }}
+
+      - name: Setup rm-symlink alias
+        if: contains(runner.os, 'windows')
+        shell: bash
+        run: |
+          git config --global alias.rm-symlinks '!'"$(cat <<'ETX'
+          __git_rm_symlinks() {
+            case "$1" in (-h)
+              printf 'usage: git rm-symlinks [symlink] [symlink] [...]\n'
+              return 0
+            esac
+            ppid=$$
+            case $# in
+              (0) git ls-files -s | grep -E '^120000' | cut -f2 ;;
+              (*) printf '%s\n' "$@" ;;
+            esac | while IFS= read -r symlink; do
+              case "$symlink" in
+                (*/*) symdir=${symlink%/*} ;;
+                (*) symdir=. ;;
+              esac
+              git checkout -- "$symlink"
+              src="${symdir}/$(cat "$symlink")"
+              posix_to_dos_sed='s_^/\([A-Za-z]\)_\1:_;s_/_\\\\_g'
+              doslnk=$(printf '%s\n' "$symlink" | sed "$posix_to_dos_sed")
+              dossrc=$(printf '%s\n' "$src" | sed "$posix_to_dos_sed")
+              if [ -f "$src" ]; then
+                rm -f "$symlink"
+                cmd //C mklink //H "$doslnk" "$dossrc"
+              elif [ -d "$src" ]; then
+                rm -f "$symlink"
+                cmd //C mklink //J "$doslnk" "$dossrc"
+              else
+                printf 'error: git-rm-symlink: Not a valid source\n' >&2
+                printf '%s =/=> %s  (%s =/=> %s)...\n' \
+                    "$symlink" "$src" "$doslnk" "$dossrc" >&2
+                false
+              fi || printf 'ESC[%d]: %d\n' "$ppid" "$?"
+              git update-index --assume-unchanged "$symlink"
+            done | awk '
+              BEGIN { status_code = 0 }
+              /^ESC\['"$ppid"'\]: / { status_code = $2 ; next }
+              { print }
+              END { exit status_code }
+            '
+          }
+          __git_rm_symlinks
+          ETX
+          )"
+          git config --global alias.rm-symlink '!git rm-symlinks'  # for back-compat.
+
+      - if: contains(runner.os, 'windows')
+        shell: bash
+        run: git rm-symlink
 
       - name: Cache ivy2
         uses: actions/cache@v1
